//! Integration test: validates Rust normalize() against Python oracle output.
//!
//! Reads `tests/oracle.jsonl` (generated by `test_and_generate_oracle.py`)
//! and asserts that `bn_normalize_rs::word::normalize(input)` matches
//! `expected_normalized` for every entry.

use std::fs;
use std::path::Path;

#[test]
fn validate_against_oracle() {
    // Try oracle.jsonl first (large corpus run), fall back to builtin sample
    let oracle_path = if Path::new("tests/oracle.jsonl").exists() {
        "tests/oracle.jsonl"
    } else if Path::new("tests/oracle_builtin_sample.jsonl").exists() {
        "tests/oracle_builtin_sample.jsonl"
    } else {
        panic!(
            "No oracle file found. Run:\n  \
             cd tests && python3 test_and_generate_oracle.py [corpus.txt] [sample_size]"
        );
    };

    let contents = fs::read_to_string(oracle_path)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", oracle_path, e));

    let mut total = 0;
    let mut passed = 0;
    let mut failures: Vec<String> = Vec::new();

    for (line_num, line) in contents.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }

        // Parse JSON manually (no serde dependency needed for this simple format)
        let entry: OracleEntry = match parse_oracle_line(line) {
            Some(e) => e,
            None => {
                failures.push(format!("line {}: failed to parse JSON: {}", line_num + 1, line));
                continue;
            }
        };

        total += 1;

        let rust_result = bn_normalize_rs::word::normalize(&entry.input);

        if rust_result == entry.expected_normalized {
            passed += 1;
        } else {
            failures.push(format!(
                "MISMATCH line {}: input={:?}  expected={:?}  got={:?}",
                line_num + 1,
                entry.input,
                entry.expected_normalized,
                rust_result,
            ));
        }
    }

    eprintln!("\n=== Oracle validation: {} ===", oracle_path);
    eprintln!("Total: {}  Passed: {}  Failed: {}", total, passed, failures.len());

    if !failures.is_empty() {
        eprintln!("\nFailures:");
        for (i, f) in failures.iter().enumerate() {
            eprintln!("  {}. {}", i + 1, f);
            if i >= 49 {
                eprintln!("  ... and {} more", failures.len() - 50);
                break;
            }
        }
        panic!(
            "{}/{} oracle entries failed. See stderr output above.",
            failures.len(),
            total
        );
    }
}

// ─── Minimal JSON parser (avoids adding serde as a dependency) ────────

struct OracleEntry {
    input: String,
    expected_normalized: Option<String>,
}

fn parse_oracle_line(line: &str) -> Option<OracleEntry> {
    // Format: {"input": "...", "expected_normalized": "..." or null}
    let line = line.trim();
    if !line.starts_with('{') || !line.ends_with('}') {
        return None;
    }

    let input = extract_json_string(line, "input")?;
    let expected = extract_json_string_or_null(line, "expected_normalized");

    Some(OracleEntry {
        input,
        expected_normalized: expected,
    })
}

fn extract_json_string(json: &str, key: &str) -> Option<String> {
    let pattern = format!("\"{}\":", key);
    let start = json.find(&pattern)? + pattern.len();
    let rest = json[start..].trim_start();

    if rest.starts_with('"') {
        let inner = &rest[1..];
        let end = find_unescaped_quote(inner)?;
        Some(inner[..end].replace("\\\"", "\"").replace("\\\\", "\\"))
    } else {
        None
    }
}

fn extract_json_string_or_null(json: &str, key: &str) -> Option<String> {
    let pattern = format!("\"{}\":", key);
    let start = json.find(&pattern)? + pattern.len();
    let rest = json[start..].trim_start();

    if rest.starts_with("null") {
        None
    } else if rest.starts_with('"') {
        let inner = &rest[1..];
        let end = find_unescaped_quote(inner)?;
        Some(inner[..end].replace("\\\"", "\"").replace("\\\\", "\\"))
    } else {
        None
    }
}

fn find_unescaped_quote(s: &str) -> Option<usize> {
    let mut i = 0;
    let bytes = s.as_bytes();
    while i < bytes.len() {
        if bytes[i] == b'"' {
            return Some(i);
        }
        if bytes[i] == b'\\' {
            i += 2;
        } else {
            i += 1;
        }
    }
    None
}
